export const tweetsData = [   
    {
        handle: `@Njoku_Script 💎`,
        profilePic: `images/njo.jpg`,
        likes: 27,
        retweets: 10,
        tweetText: `Javascript is so simple and fun. I find it really easy working with JS. My advice for 2023 is try and learn a digital skill`,
        replies: [],
        isLiked: false,
        isRetweeted: false,
        uuid: `5d80db79-6b9d-4a0b-92f6-43e3b9ddbd56`,
    }, 
        {
        handle: `@Mfon_Udo ✅`,
        profilePic: `images/lt.jpg`,
        likes: 278,
        retweets: 102,
        tweetText: `Good morning guys😎 We go again. Keep believing`,
        replies: [
            {
                handle: `@LT Emmanuel`,
                profilePic: `images/mfon.jpg`,
                tweetText: `Never giving up 👩🏼‍💻`,
            },
                  {
                handle: `@Zichat Bakam`,
                profilePic: `images/baka.jpg`,
                tweetText: `Yuup! 😎🛩`,
            },
                   {
                handle: `@Ukorebi`,
                profilePic: `images/overflow.png`,
                tweetText: `We're good 🕵🏼`,
            },
            
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: `61631cfb-ef86-47fb-bb69-52a5e98ba19b`,
    },
    { 
            handle: `@Kingdomcop ✅`,
        profilePic: `images/cop.jpg`,
        likes: 650,
        retweets: 24,
        tweetText: `Let's talk business 🚀 I offer profelicities at a cheaper rate 😊 Unbelievable right? You're just a dm away.`,
        replies: [
                  {
                handle: `@EtyScript ✅`,
                profilePic: `images/h.jpg`,
                tweetText: `Mad dentition 😁`,
            },
                  {
                handle: `@diana ✅`,
                profilePic: `images/diana.jpg`,
                tweetText: `Yes! Sign me up! 😎🛩`,
            },
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: `83f8708b-d039-4bbc-9ab6-da6697853b19`,
    },  
    {
        handle: `@Elon ✅`,
        profilePic: `images/musk.png`,
        likes: 6500,
        retweets: 234,
        tweetText: `I need volunteers for a one-way mission to Mars 🪐. No experience necessary🚀`,
        replies: [
                  {
                handle: `@TomCruise ✅`,
                profilePic: `images/tcruise.png`,
                tweetText: `Yes! Sign me up! 😎🛩`,
            },
                  {
                handle: `@Pearl ✅`,
                profilePic: `images/pearl.jpg`,
                tweetText: `I need😴`,
            },
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: `ae5d45da-cd9a-436a-9ab3-cd1580a40091`,
    },
       {
        handle: `@Zeus_Crypt ✅`,
        profilePic: `images/zeus.jpg`,
        likes: 400,
        retweets: 34,
        tweetText: `Trade Binance futures this week🚀`,
        replies: [
                  {
                handle: `@TomCruise ✅`,
                profilePic: `images/tcruise.png`,
                tweetText: `Yes! We are all set 😎🛩`,
            },
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: `2eb174a2-2b62-4b74-b0db-d783b26b86de`,
    },
        {
        handle: `Mum ❤️‍`,
        profilePic: `images/love.png`,
        likes: 5500,
        retweets: 834,
        tweetText: `I pray the new month favour y'all. Amen. `,
        replies: [
                  {
                handle: `@Gracecop ✅`,
                profilePic: `images/h.jpg`,
                tweetText: `Amen. Love you Mum ❤️`,
            },
                  {
                handle: `@Khiza ✅`,
                profilePic: `images/diana.jpg`,
                tweetText: `Amen Momma 😎`,
            },
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: `86737aff-e0fe-4e5e-a771-08a2ffc433ef`,
    },
        {
        handle: `@FX_Edet`,
        profilePic: `images/all.jpg`,
        likes: 10,
        retweets: 3,
        tweetText: `Learn Forex with me. I trade for a living. Happy new year in advance`,
        replies: [
            {
                handle: `@Tom Cruise ☣️`,
                profilePic: `images/tcruise.png`,
                tweetText: `Here we go again 💨`,
            },
            {
                handle: `@YummyCoder64`,
                profilePic: `images/love.png`,
                tweetText: `Alright ❤️`,
            },
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: `508944b7-79be-47f3-b009-cb73f09fd393`,
    },     
]